# Generated by Django 6.0.6 on 2026-06-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('people', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
